name: action

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env: 
      CLOUD_RUN_SERVICE: https://hello-551258563214.us-central1.run.app

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      id: auth
      with:
        workload_identity_provider: 'projects/551258563214/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'github-action-sa@glasnt-github-auth-5815.iam.gserviceaccount.com'
        id_token_audience: ${{ env.CLOUD_RUN_SERVICE }}
        id_token_include_email: true
        token_format: 'id_token'
    - id: get-service
      run: |-
        curl -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" ${{ env.CLOUD_RUN_SERVICE }} --fail-with-body
